Repository alist-org/alist-web, pull requests merged in 2023-08, with the labels that each got.

#101 fix(Notify): 修复关闭按钮和文字重合的问题 & feat(Rename): 重命名时默认选中后缀名前的部分
  src/components/ModalInput.tsx
  src/pages/home/toolbar/Rename.tsx
  src/utils/notify.tsx
Labels: size/M

#103 feat(search):Supports file search or dir search
  src/components/Base.tsx
  src/lang/en/home.json
  src/pages/home/folder/Search.tsx
  src/utils/api.ts
Labels: size/M

#106 fix: Incorrect current page of search paginator
  src/pages/home/folder/Search.tsx
Labels: size/S

#104 feat: support webauthn login
  package.json
  pnpm-lock.yaml
  src/lang/en/settings.json
  src/lang/en/users.json
  src/pages/login/index.tsx
  src/pages/manage/users/Profile.tsx
  src/pages/manage/users/Webauthnitems.tsx
Labels: size/L

#109 Modify epub static resource link
  public/static/epub.js/viewer.html
Labels: size/XS

#110 预览文本支持GB2312
  src/components/EncodingSelect.tsx
  src/components/Markdown.tsx
  src/components/MonacoEditor.tsx
  src/components/index.ts
  src/hooks/useUtil.ts
  src/pages/home/Readme.tsx
  src/pages/home/previews/html.tsx
  src/pages/home/previews/markdown.tsx
  src/pages/home/previews/markdown_with_word_wrap.tsx
  src/pages/home/previews/text-editor.tsx
  src/pages/home/previews/url.tsx
  src/utils/api.ts
  src/utils/str.ts
Labels: size/L
