Repository alist-org/alist-web, pull requests merged in 2024-05, with the labels that each got.

#164 Encode URL param for external player
  src/pages/home/previews/video_box.tsx
Labels: size/XS

#167 fix: incorrect search results link with `#` (close alist-org/alist#6234)
  src/pages/home/folder/Search.tsx
Labels: size/XS

#170 fix: base path for relative path in markdown
  src/components/Markdown.tsx
  src/utils/path.ts
Labels: size/S

#169 feat: add supports for netease music driver
  src/lang/en/drivers.json
  src/pages/home/previews/audio.tsx
Labels: size/M

#168 feat: playlist download
  src/hooks/useDownload.ts
  src/lang/en/home.json
  src/pages/home/folder/context-menu.tsx
  src/pages/home/toolbar/Download.tsx
Labels: size/M

#171 feat: support search for select component
  src/components/SelectOptions.tsx
  src/components/index.ts
  src/pages/manage/storages/AddOrEdit.tsx
  src/pages/manage/storages/Item.tsx
Labels: size/L

#173 fix: show last selected folder on copy/move modal
  src/components/FolderTree.tsx
Labels: size/S

#176 refactor: support media titles in m3u8 playlist
  src/hooks/useDownload.ts
  src/pages/home/folder/context-menu.tsx
  src/pages/home/toolbar/Download.tsx
Labels: size/M

#178 chore: add `proxy_range` `proxy_range-tips` for storages
  src/lang/en/storages.json
Labels: size/XS

#174 style: Search Box
  src/pages/home/header/Header.tsx
Labels: size/XS
