Repository alist-org/alist-web, pull requests merged in 2024-03, with the labels that each got.

#154 fix: additional logic of optional open item on checkbox
  src/pages/home/folder/GridItem.tsx
  src/pages/home/folder/ImageItem.tsx
  src/pages/home/folder/ListItem.tsx
  src/pages/home/folder/helper.ts
  src/store/local_settings.ts
Labels: size/S

#152 feat!: s3 server
  src/lang/en/global.json
  src/lang/en/manage.json
  src/lang/en/settings.json
  src/pages/manage/settings/S3.tsx
  src/pages/manage/settings/S3BucketItem.tsx
  src/pages/manage/settings/S3Buckets.tsx
  src/pages/manage/sidemenu_items.tsx
  src/types/setting.ts
Labels: size/L

#157 feat: select with mouse while checkbox closed
  package.json
  pnpm-lock.yaml
  src/app/theme.ts
  src/lang/en/home.json
  src/pages/home/folder/Grid.tsx
  src/pages/home/folder/GridItem.tsx
  src/pages/home/folder/ImageItem.tsx
  src/pages/home/folder/Images.tsx
  src/pages/home/folder/List.tsx
  src/pages/home/folder/ListItem.tsx
  src/pages/home/folder/context-menu.tsx
  src/pages/home/folder/helper.ts
  src/store/local_settings.ts
Labels: size/XL

#159 feat: better error handling of webauthn
  src/pages/login/index.tsx
  src/pages/manage/users/Profile.tsx
Labels: size/M

#155 fix: hide matched files/folders in sidebar
  src/components/FolderTree.tsx
  src/hooks/useUtil.ts
  src/pages/home/Sidebar.tsx
Labels: size/L

#158 fix: needless editor reload on content change
  package.json
  pnpm-lock.yaml
  src/pages/home/previews/text-editor.tsx
Labels: size/L

#161 feat: better action of checkbox on mobile phone
  src/app/theme.ts
  src/lang/en/home.json
  src/pages/home/folder/Folder.tsx
  src/pages/home/folder/GridItem.tsx
  src/pages/home/folder/ImageItem.tsx
  src/pages/home/folder/List.tsx
  src/pages/home/folder/ListItem.tsx
  src/pages/home/folder/helper.ts
  src/pages/home/toolbar/LocalSettings.tsx
  src/store/local_settings.ts
Labels: size/M
