Repository alist-org/alist-web, pull requests merged in 2024-02, with the labels that each got.

#140 feat: encrypted backup and restore
  package.json
  pnpm-lock.yaml
  src/lang/en/br.json
  src/pages/manage/backup-restore.tsx
Labels: size/L

#147 fix: paused video will play automatically after switching url
  src/pages/home/previews/aliyun_video.tsx
Labels: size/XS

#146 feat: add sidebar of folder tree
  src/components/FolderTree.tsx
  src/components/Markdown.tsx
  src/lang/en/home.json
  src/pages/home/Body.tsx
  src/pages/home/Obj.tsx
  src/pages/home/Sidebar.tsx
  src/store/local_settings.ts
  src/utils/path.ts
Labels: size/L

#149 feat: make long file name scrollable
  src/lang/en/home.json
  src/pages/home/folder/ListItem.tsx
  src/pages/home/toolbar/LocalSettings.tsx
  src/store/local_settings.ts
Labels: size/S

#148 feat: block actions of router while checkbox enabled
  src/pages/home/folder/GridItem.tsx
  src/pages/home/folder/ImageItem.tsx
  src/pages/home/folder/ListItem.tsx
Labels: size/M

#153 fix: disable markdown toc on default
  src/components/Markdown.tsx
Labels: size/XS
